### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by amgno** [pfgithub/interpunctbot#58]

**Comment by pfgithub** [comment]
the vps I'm running it on isn't powerful enough for docker so I haven't done it yet. It shouldn't be too difficult to make a docker setup for the bot and database.

**Comment by amgno** [comment]
Oh I see, if you need a free vps I suggest trying the Oracle always free plan.
I'll try and see if I can make a Dockerfile

**Comment by amgno** [comment]
Tried with a Dockerfile like this:
```
FROM node:16.9

COPY * /bot/
RUN corepack enable
RUN cd /bot/ && yarn install


CMD ["node", "built"]
```

But got this:
```
Step 4/5 : RUN cd /bot/ && yarn install
 ---> Running in 3405c8bae694
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/bot/.yarn/releases/yarn-berry.cjs'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by pfgithub** [comment]
@heryoff I think `*` is excluding files starting with `.`, maybe `COPY . /bot/` will work?:

```Dockerfile
FROM node:16.9

COPY . /bot/
WORKDIR /bot
RUN corepack enable
RUN yarn install
RUN yarn tsc


CMD ["node", "built"]
```

https://stackoverflow.com/questions/30215830/dockerfile-copy-keep-subdirectory-structure

**Comment by amgno** [comment]
@pfgithub Ok, made it work, only thing is that now I get an error when trying to run "node built".
```
test_1  | node:internal/modules/cjs/loader:936
test_1  |   throw err;
test_1  |   ^
test_1  | 
test_1  | Error: Cannot find module '/build'
test_1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
test_1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
test_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
test_1  |     at node:internal/main/run_main_module:17:47 {
test_1  |   code: 'MODULE_NOT_FOUND',
test_1  |   requireStack: []
test_1  | }
interpunctbot_test_1 exited with code 1
```

**Comment by amgno** [comment]
Updated Dockerfile
```Dockerfile                                                    
FROM node:16.9

COPY . /bot/
RUN corepack enable
RUN cd /bot/ && yarn install

CMD ["yarn", "knex", "migrate:latest"]
CMD ["yarn", "build-watch"]
CMD ["node", "build"]


```

**Comment by pfgithub** [comment]
@heryoff That looks pretty good I think. Instead of 'build-watch', you can put

```Dockerfile
RUN yarn tsc
```

Also, you'll want to make sure the database is stored outside of the docker container if it's configured to sqlite. Probably the config files too. I forgot if that's only part of the docker command or if it goes in the dockerfile too.

**Comment by amgno** [comment]
@pfgithub I see, nice. Even tho I don't really get the last part:

> Also, you'll want to make sure the database is stored outside of the docker container if it's configured to sqlite. Probably the config files too. I forgot if that's only part of the docker command or if it goes in the dockerfile too.

And I still get this error
```
Attaching to interpunctbot_test_1
test_1  | node:internal/modules/cjs/loader:936
test_1  |   throw err;
test_1  |   ^
test_1  | 
test_1  | Error: Cannot find module '/built'
test_1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
test_1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
test_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
test_1  |     at node:internal/main/run_main_module:17:47 {
test_1  |   code: 'MODULE_NOT_FOUND',
test_1  |   requireStack: []
test_1  | }
interpunctbot_test_1 exited with code 1
```

**Comment by pfgithub** [comment]
@heryoff you need to set `WORKDIR /bot` for the run command to work

> Even tho I don't really get the last part

https://docs.docker.com/storage/bind-mounts/ It's called a bind mount it looks like - so you can publish the docker container and someone else can run it with their own config and data in the database can be kept across destroying and recreating the container

**Comment by amgno** [comment]
@pfgithub Yeah I did that yersterday and still didn't work.
Got that last part, I'll work on it when the bot works

**Comment by amgno** [comment]
Ok did some digging and find out I had issues with the distro I currencty host Docker on.
Change it to Ubuntu and now it seems to work. I'll try to make it as optimized as I can, I'll post the files here once finished

**Comment by amgno** [comment]
@pfgithub 
I get this error now:
(I know nothing about node, so I really can't figure it out)
```
Attaching to interpunctbot_test_1
test_1  | Starting inter·punct bot
test_1  | Loading commands...
test_1  | (node:1) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
test_1  | (Use `node --trace-warnings ...` to show where the warning was created)
test_1  | All commands loaded (192 commands, 217 docs entries)
test_1  | Sub-command knots does not have a command
test_1  | Sub-command tic does not have a command
test_1  | Sub-command tick does not have a command
test_1  | Sub-command tick does not have a command
test_1  | Sub-command ultimate does not have a command
test_1  | Sub-command ultimate/tic does not have a command
test_1  | Sub-command big does not have a command
test_1  | Sub-command big/tic does not have a command
test_1  | Sub-command ultimate does not have a command
test_1  | Sub-command ultimate/knots does not have a command
test_1  | Sub-command big does not have a command
test_1  | Sub-command big/knots does not have a command
test_1  | Sub-command infinite does not have a command
test_1  | Sub-command infinite/tic does not have a command
test_1  | Sub-command set does not have a command
test_1  | Sub-command set does not have a command
test_1  | Sub-command set/show does not have a command
test_1  | [WS => Manager] Fetched Gateway Information
test_1  |     URL: wss://gateway.discord.gg
test_1  |     Recommended Shards: 1
test_1  | [WS => Manager] Session Limit Information
test_1  |     Total: 1000
test_1  |     Remaining: 999
test_1  | [WS => Manager] Spawning shards: 0
test_1  | [WS => Shard 0] [CONNECT]
test_1  |     Gateway    : wss://gateway.discord.gg/
test_1  |     Version    : 10
test_1  |     Encoding   : json
test_1  |     Compression: none
test_1  | [WS => Shard 0] Setting a HELLO timeout for 20s.
test_1  | [WS => Shard 0] [CONNECTED] Took 277ms
test_1  | [WS => Shard 0] Clearing the HELLO timeout.
test_1  | [WS => Shard 0] Setting a heartbeat interval for 41250ms.
test_1  | [WS => Shard 0] [IDENTIFY] Shard 0/1 with intents: 46607
test_1  | [WS => Shard 0] Clearing the heartbeat interval.
test_1  | [WS => Shard 0] [CLOSE]
test_1  |     Event Code: 4014
test_1  |     Clean     : true
test_1  |     Reason    : Disallowed intent(s).
test_1  | [WS => Shard 0] DisallowedIntents
test_1  | [WS => Manager] Manager was destroyed. Called by:
test_1  | Error
test_1  |     at WebSocketManager.destroy (/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:323:54)
test_1  |     at Client.destroy (/bot/node_modules/discord.js/src/client/Client.js:257:13)
test_1  |     at Client.login (/bot/node_modules/discord.js/src/client/Client.js:235:12)
test_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
test_1  | [WS => Shard 0] [WebSocket] Destroy: Attempting to close the WebSocket. | WS State: CLOSED
test_1  | [WS => Shard 0] WS State: CLOSED
test_1  | [WS => Shard 0] [WebSocket] Adding a WebSocket close timeout to ensure a correct WS reconnect.
test_1  |         Timeout: 5000ms
test_1  | UNHANDLED REJECTON. Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
test_1  |     at WebSocketManager.createShards (/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
test_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
test_1  |     at async Client.login (/bot/node_modules/discord.js/src/client/Client.js:232:7) {
test_1  |   code: 'DisallowedIntents'
test_1  | } Promise {
test_1  |   <rejected> Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
test_1  |       at WebSocketManager.createShards (/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
test_1  |       at processTicksAndRejections (node:internal/process/task_queues:96:5)
test_1  |       at async Client.login (/bot/node_modules/discord.js/src/client/Client.js:232:7) {
test_1  |     code: 'DisallowedIntents'
test_1  |   }
test_1  | }
test_1  | [WS => Shard 0] [WebSocket] Clearing the close timeout.
test_1  | [WS => Shard 0] [WebSocket] Close Emitted: false
test_1  | [WS => Shard 0] [WebSocket] did not close properly, assuming a zombie connection.
test_1  | Emitting close and reconnecting again.
test_1  | [WS => Shard 0] [CLOSE]
test_1  |     Event Code: 1011
test_1  |     Clean     : false
test_1  |     Reason    : INTERNAL_ERROR

```

**Comment by pfgithub** [comment]
Oh, it looks like the readme is missing information

> Privileged intent provided is not enabled or whitelisted.

This means in the discord.com/developers/applications/me page, you have to go to the bot and enable message content and guild members

**Comment by amgno** [comment]
Perfect, everything now works. I'll try and see if I can make the config files stay outside the docker build

**Comment by amgno** [comment]
@pfgithub Just did some testing with my Windows machine and trying to run the exact same dockerfile result in this:
```
 => ERROR [7/7] RUN yarn tsc                                                                                      20.3s
------
 > [7/7] RUN yarn tsc:
#0 1.497 yarn run v1.22.11
#0 1.611 $ /bot/node_modules/.bin/tsc
#0 20.20 src/commands/fun/goi.ts(160,8): error TS18048: 'gamedata' is possibly 'undefined'.
#0 20.20 src/commands/fun/goi.ts(160,17): error TS2339: Property 'emojis' does not exist on type 'string | object'.
#0 20.20   Property 'emojis' does not exist on type 'string'.
#0 20.20 src/commands/fun/goi.ts(161,15): error TS18048: 'gamedata' is possibly 'undefined'.
#0 20.20 src/commands/fun/goi.ts(161,24): error TS2339: Property 'levels' does not exist on type 'string | object'.
#0 20.20   Property 'levels' does not exist on type 'string'.
#0 20.20 src/commands/fun/goi.ts(162,22): error TS18048: 'gamedata' is possibly 'undefined'.
#0 20.20 src/commands/fun/goi.ts(162,31): error TS2339: Property 'start' does not exist on type 'string | object'.
#0 20.20   Property 'start' does not exist on type 'string'.
#0 20.20 src/commands/fun/spyfall.ts(29,7): error TS2322: Type 'string | object | undefined' is not assignable to type 'GameData'.
#0 20.20   Type 'undefined' is not assignable to type 'GameData'.
#0 20.24 error Command failed with exit code 2.
#0 20.24 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn tsc]: exit code: 2
```

**Comment by amgno** [comment]
Ok I made it work, it works everywhere I tried, even added a mount to ./config so that you don't need to rebuild it everytime.
How can I give the files to you?

**Comment by pfgithub** [comment]
If you know how to use git, you can create a pull request in this repository:
- Commit and push your changes to your fork of this repository
- Create a new pull request here, select "compare across forks", choose your repository and branch and it should show the changes you made and let you make a pull request

Alternatively, you can upload files as gists: https://gist.github.com/ and I can add them to the repository myself

**Comment by pfgithub** [comment]
#59
